name: .NET Build, Test, and Integration with PostgreSQL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: dev
          POSTGRES_DB: testdb
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: 🧪 [Email Service] Tests 
      run: dotnet test Xcel.Services.Email.Tests/Xcel.Services.Email.Tests.csproj
    - name: 🧪 [Auth Service] Tests 
      run: dotnet test Xcel.Services.Auth.Tests/Xcel.Services.Auth.Tests.csproj
    - name: 🧪 Integration Tests - Infra
      run: dotnet test Domain.IntegrationTests/Domain.IntegrationTests.csproj
